import { Loader2, AlertCircle, CheckCircle2, GitPullRequest } from 'lucide-react';
import MarkdownPreview from '@uiw/react-markdown-preview';

interface PRSummaryTabProps {
  pr: any;
  review: any;
  reviewStatus: 'idle' | 'running' | 'success' | 'error';
  reviewMessage: string;
}

export function PRSummaryTab({ pr, review, reviewStatus, reviewMessage }: PRSummaryTabProps) {
  const markdownContent = review?.summary
    ? review.summary
    : pr?.body
      ? pr.body
      : `# ${pr?.title || 'Pull Request'}\n\nNo description provided.`;

  const prMeta = pr
    ? `**Author:** ${pr.user?.login || 'unknown'} · **Base:** \`${pr.base?.ref || 'main'}\` ← \`${pr.head?.ref || 'feature'}\` · **Status:** ${pr.state || 'open'}\n\n---\n\n`
    : '';

  return (
    <div className="h-full bg-background overflow-y-auto w-full">
      <div className="p-8 max-w-3xl mx-auto w-full">

        {/* Review generation status banner */}
        {reviewStatus === 'running' && (
          <div className="mb-6 flex items-center gap-2 text-sm text-muted-foreground bg-muted/40 border border-border rounded-md px-4 py-3">
            <Loader2 className="w-4 h-4 animate-spin shrink-0" />
            <span className="font-mono text-xs">{reviewMessage || 'Generating AI review...'}</span>
          </div>
        )}
        {reviewStatus === 'error' && (
          <div className="mb-6 flex items-center gap-2 text-sm text-destructive bg-destructive/5 border border-destructive/20 rounded-md px-4 py-3">
            <AlertCircle className="w-4 h-4 shrink-0" />
            <span>Review generation failed: {reviewMessage}</span>
          </div>
        )}
        {reviewStatus === 'success' && review && (
          <div className="mb-4 flex items-center gap-2 text-sm text-green-500">
            <CheckCircle2 className="w-4 h-4 shrink-0" />
            <span>AI review generated · Verdict: <strong>{review.overallVerdict?.replace('_', ' ')}</strong></span>
          </div>
        )}

        {/* PR header info */}
        {pr && (
          <div className="flex items-center gap-2 mb-6 p-3 bg-muted/20 border border-border rounded-md text-sm text-muted-foreground">
            <GitPullRequest className="w-4 h-4 shrink-0" />
            <span>
              <strong className="text-foreground">{pr.user?.login}</strong>
              {' '}wants to merge into{' '}
              <code className="bg-muted px-1.5 py-0.5 rounded font-mono text-xs">{pr.base?.ref || 'main'}</code>
              {' '}from{' '}
              <code className="bg-muted px-1.5 py-0.5 rounded font-mono text-xs">{pr.head?.ref || 'feature'}</code>
            </span>
          </div>
        )}

        <MarkdownPreview
          source={prMeta + markdownContent}
          style={{ backgroundColor: 'transparent' }}
          className="text-sm! md:text-base! w-full"
        />

        {reviewStatus === 'success' && review && !review.summary.includes('\n') && (
          <p className="mt-4 text-xs text-muted-foreground italic">
            *Summary generated by local AI based on the PR diff and architectural context.*
          </p>
        )}
      </div>
    </div>
  );
}
